{"frames":[{"character_number":0,"end_character_number":0,"end_line_number":0,"file":"","func":"dbConnect(drv = PostgreSQL(max.con = 1), user = remote_omni_postgresql_username, \n    password = remote_omni_postgresql_username, dbname = \"cjitjeca\", \n    host = \"34.245.37.126\")","line_number":0},{"character_number":0,"end_character_number":0,"end_line_number":0,"file":"","func":"dbConnect(drv = PostgreSQL(max.con = 1), user = remote_omni_postgresql_username, \n    password = remote_omni_postgresql_username, dbname = \"cjitjeca\", \n    host = \"34.245.37.126\")","line_number":0},{"character_number":0,"end_character_number":0,"end_line_number":0,"file":"","func":"postgresqlNewConnection(drv, ...)","line_number":0}],"message":"Error in postgresqlNewConnection(drv, ...) : \n  RS-DBI driver: (could not connect cjitjeca@34.245.37.126:5432 on dbname \"cjitjeca\": FATAL:  password authentication failed for user \"cjitjeca\"\n)\n"}